// Code generated by "stringer -type=PhoneNumberType"; DO NOT EDIT.

package phonenumbers

import "strconv"

const _PhoneNumberType_name = "FIXED_LINEMOBILEFIXED_LINE_OR_MOBILETOLL_FREEPREMIUM_RATESHARED_COSTVOIPPERSONAL_NUMBERPAGERUANVOICEMAILUNKNOWN"

var _PhoneNumberType_index = [...]uint8{0, 10, 16, 36, 45, 57, 68, 72, 87, 92, 95, 104, 111}

func (i PhoneNumberType) String() string {
	if i < 0 || i >= PhoneNumberType(len(_PhoneNumberType_index)-1) {
		return "PhoneNumberType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PhoneNumberType_name[_PhoneNumberType_index[i]:_PhoneNumberType_index[i+1]]
}
